name: Continuous Integration

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    if: github.event.ref == 'refs/heads/finetune_release'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with: # configure settings.xml
        distribution: 'temurin'
        java-version: '11'
        server-id: ossrh
        server-username: OSSRH_USER
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.ORG_GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE

    - name: Build and Publish to Apache Maven Central
      run: mvn clean deploy
      env:
        OSSRH_USER: ${{ secrets.ORG_OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.ORG_GPG_PASSPHRASE }}
